services:
  candlemind:
    build:
      context: .
      dockerfile: Dockerfile
    image: candlemind:latest
    container_name: candlemind
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
